Repository modrinth/code, pull requests merged in 2025-04, with the labels that each got.

#3494 Fix Clippy lints
  apps/daedalus_client/src/forge.rs
  apps/labrinth/src/models/v3/billing.rs
  apps/labrinth/src/routes/v2/version_creation.rs
  apps/labrinth/src/routes/v3/version_file.rs
  packages/app-lib/src/api/pack/import/curseforge.rs
  packages/app-lib/src/util/io.rs
Labels: DevEx

#3492 Remove unused Rust dependencies
  Cargo.lock
  apps/app-playground/Cargo.toml
  apps/app/Cargo.toml
  apps/daedalus_client/Cargo.toml
  apps/labrinth/Cargo.toml
  packages/app-lib/Cargo.toml
  packages/daedalus/Cargo.toml
Labels: enhancement, DevEx

#3544 Disable Labrinth hCaptcha verification when secret is unset
  apps/labrinth/src/util/captcha.rs
Labels: backend, DevEx

#3545 Proper Clickhouse user setup for local Labrinth development
  apps/labrinth/.env
  docker-compose.yml
Labels: backend, DevEx

#2886 feat(labrinth): environment variables for more customizable SMTP
  apps/labrinth/.env
  apps/labrinth/src/auth/email/mod.rs
  apps/labrinth/src/lib.rs
Labels: backend, DevEx
